### ISSUE TITLE
Any ideas on how to generate depth map faster?

### ISSUE THREAD

**Issue by nvinhphuc** [YadiraF/PRNet#122]
I have to generate depth-map for a large dataset, so I need to do it faster.
According to my observation, the depth map generation is slow because of the z-buffer algorithm run on CPU (costs 3s per image), while the PRNet process the vertices from the image so fast. So I wonder if there are any ways to faster the process (multi-thread, multi-core, etc.)?

**Comment by nwdxbx** [comment]
@intheroom hi,I also want get the depth map,can you tell me how to get it, thanks!

**Comment by nvinhphuc** [comment]
> @intheroom hi,I also want get the depth map,can you tell me how to get it, thanks!

you can use this command:
python demo.py -i <inputDir> -o <outputDir> --isDlib True --isDepth True

**Comment by nwdxbx** [comment]
@intheroom Thank you ver much. I will try it soon.

**Comment by zhuomanliu** [comment]
I tried this cython version [https://github.com/YadiraF/face3d/tree/master/face3d/mesh] for generating depth maps, and it only cost 0.0035s per frame.

**Comment by zhuomanliu** [comment]
I tried the [cython version](https://github.com/YadiraF/face3d/tree/master/face3d/mesh) for generating depth maps, and it only cost 0.0035s per frame.

**Comment by Guyume** [comment]
@zhuomanliu  I have the same problem of generating depth map, but I am new to pyhton, does the  cython version have the source code of getting depth map or should write a new function, can you give me some hint?

**Comment by baoyu-yuan** [comment]
@zhuomanliu hello, I have try the code you referred to generate depth image, but I get different results with the original z-buffer code here. Have you ever encountered this situation ?

**Comment by gjd2017** [comment]
@zhuomanliu @baorave, I also encounter this situation.

**Comment by punitha-valli** [comment]
@baorave 
@nwdxbx @intheroom @zhuomanliu @Guyume 

can any one help me to get the dept map of my dataset,

because i always get this error

Traceback (most recent call last):
  File "E:/yzu/lab/face anti spoofing/PRNet-master/demo.py", line 168, in <module>
    main(parser.parse_args())
  File "E:/yzu/lab/face anti spoofing/PRNet-master/demo.py", line 56, in main
    pos = prn.process(image) # use dlib to detect face
  File "E:\yzu\lab\face anti spoofing\PRNet-master\api.py", line 101, in process
    detected_faces = self.dlib_detect(image)
  File "E:\yzu\lab\face anti spoofing\PRNet-master\api.py", line 55, in dlib_detect
    return self.face_detector(image, 1)
RuntimeError: Unsupported image type, must be 8bit gray or RGB image.


but my images are RGB images, i just make a check of it. still now i get this error
