### ISSUE TITLE
Can not run demo.py

### ISSUE THREAD

**Issue by manfonly** [YadiraF/PRNet#158]
I have installed dependency by:
pip3 install -r requirements.txt

Then I can run "python3 run_basics.py", although got lots of warnings:
tree
.
├── 0.jpg
├── 1.jpg
├── 2.jpg
├── 3.jpg
├── 4.jpg
├── 5.jpg
├── AFLW2000
│   ├── image00050.jpg
│   ├── image00050.mat
│   ├── image00081.jpg
│   ├── image00081.mat
│   ├── image00251.jpg
│   ├── image00251.mat
│   ├── image00430.jpg
│   ├── image00430.mat
│   ├── image00475.jpg
│   ├── image00475.mat
│   ├── image00514.jpg
│   ├── image00514.mat
│   ├── image00516.jpg
│   ├── image00516.mat
│   ├── image01038.jpg
│   ├── image01038.mat
│   ├── image01322.jpg
│   ├── image01322.mat
│   ├── image02283.jpg
│   ├── image02283.mat
│   ├── image02420.jpg
│   ├── image02420.mat
│   ├── image02545.jpg
│   ├── image02545.mat
│   ├── image02616.jpg
│   ├── image02616.mat
│   ├── image03324.jpg
│   ├── image03324.mat
│   ├── image03614.jpg
│   ├── image03614.mat
│   ├── image04331.jpg
│   └── image04331.mat
├── AFLW2000_results
│   ├── image00050_mesh.mat
│   ├── image00050.obj
│   ├── image00050.txt
│   ├── image00081_mesh.mat
│   ├── image00081.obj
│   ├── image00081.txt
│   ├── image00251_mesh.mat
│   ├── image00251.obj
│   ├── image00251.txt
│   ├── image00430_mesh.mat
│   ├── image00430.obj
│   ├── image00430.txt
│   ├── image00475_mesh.mat
│   ├── image00475.obj
│   ├── image00475.txt
│   ├── image00514_mesh.mat
│   ├── image00514.obj
│   ├── image00514.txt
│   ├── image00516_mesh.mat
│   ├── image00516.obj
│   ├── image00516.txt
│   ├── image01038_mesh.mat
│   ├── image01038.obj
│   ├── image01038.txt
│   ├── image01322_mesh.mat
│   ├── image01322.obj
│   ├── image01322.txt
│   ├── image02283_mesh.mat
│   ├── image02283.obj
│   ├── image02283.txt
│   ├── image02420_mesh.mat
│   ├── image02420.obj
│   ├── image02420.txt
│   ├── image02545_mesh.mat
│   ├── image02545.obj
│   ├── image02545.txt
│   ├── image02616_mesh.mat
│   ├── image02616.obj
│   ├── image02616.txt
│   ├── image03324_mesh.mat
│   ├── image03324.obj
│   ├── image03324.txt
│   ├── image03614_mesh.mat
│   ├── image03614.obj
│   ├── image03614.txt
│   ├── image04331_mesh.mat
│   ├── image04331.obj
│   └── image04331.txt

But when I run "python3 demo.py -i input_dir -o output_dir --isDlib True", I got following error and stopped:
Use standard file APIs to check for files with this prefix.
Traceback (most recent call last):
  File "demo.py", line 167, in <module>
    main(parser.parse_args())
  File "demo.py", line 55, in main
    pos = prn.process(image) # use dlib to detect face
  File "/home/matrix/workspace/PRNet/api.py", line 120, in process
    cropped_pos = self.net_forward(cropped_image)
  File "/home/matrix/workspace/PRNet/api.py", line 62, in net_forward
    return self.pos_predictor.predict(image)
  File "/home/matrix/workspace/PRNet/predictor.py", line 98, in predict
    feed_dict = {self.x: image[np.newaxis, :,:,:]})
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1149, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (1, 256, 256, 1) for Tensor 'Placeholder:0', which has shape '(?, 256, 256, 3)'

I have another question, which type of images can I put into input_dir? I just put one front face portrait in the input_dir.

**Comment by manfonly** [comment]
I changed my input picture resolution below 1000x1000, and all demo scripts can work.
