### ISSUE TITLE
ImportError: No module named 'render'

### ISSUE THREAD

**Issue by Sugarbank** [YadiraF/PRNet#27]
Hi,
Has anyone had this error?
Traceback (most recent call last):
  File "demo.py", line 15, in <module>
    from utils.render_app import get_visibility, get_uv_mask, get_depth_image
  File "C:\Users\PRNet-master\utils\render_app.py", line 2, in <module>
    from render import vis_of_vertices, render_texture
Im  using python 3 and have done the fixes to "w" Also python run_basics.py runs fine.

Thanks in advance

**Comment by markoliverbrawn** [comment]
Yep, I've got the same issue - Python 3

**Comment by seranus** [comment]
change

`from render import vis_of_vertices, render_texture` 
to
`from utils.render import vis_of_vertices, render_texture`

**Comment by markoliverbrawn** [comment]
Thanks Seranus

**Comment by cclauss** [comment]
@seranus Would you be willing to create a pull request on this change??  Python 3 does not like relative imports http://portingguide.readthedocs.io/en/latest/imports.html?highlight=absolute%20imports
