### ISSUE TITLE
CV2 seamlessClone error in demo_texture.py

### ISSUE THREAD

**Issue by rosenb0rg** [YadiraF/PRNet#32]
I get this error when I run the latest demo_texture.py :

`Traceback (most recent call last):
  File "demo_texture.py", line 101, in <module>
    texture_editing(prn, parser.parse_args())
  File "demo_texture.py", line 76, in texture_editing
    output = cv2.seamlessClone((new_image*255).astype(np.uint8), (image*255).astype(np.uint8), (face_mask*255).astype(np.uint8), center, cv2.NORMAL_CLONE)
AttributeError: 'module' object has no attribute 'seamlessClone'
`

**Comment by rosenb0rg** [comment]
The issue was solved by updating from opencv2 to opencv3 :) 

works great!
