### ISSUE TITLE
run_basics issue

### ISSUE THREAD

**Issue by jiegen** [YadiraF/PRNet#43]
Hi,

When running the 'run_basics.py' file, I get the following error:

tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ././Data/net-data/256_256_resfcn256_weight
         [[Node: save/RestoreV2_152 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_152/tensor_names, save/RestoreV2_152/shape_and_slices)]]
         [[Node: save/RestoreV2_182/_303 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_796_save/RestoreV2_182", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_basics.py", line 13, in <module>
    prn = PRN(is_dlib = False)
  File "/home/ywang/PRNet/api.py", line 34, in __init__
    self.pos_predictor.restore('./'+prn_path)
  File "/home/ywang/PRNet/predictor.py", line 94, in restore
    tf.train.Saver(self.network.vars).restore(self.sess, model_path)
  File "/home/ywang/anaconda3/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1666, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/ywang/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/home/ywang/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/ywang/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/home/ywang/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ././Data/net-data/256_256_resfcn256_weight
         [[Node: save/RestoreV2_152 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_152/tensor_names, save/RestoreV2_152/shape_and_slices)]]
         [[Node: save/RestoreV2_182/_303 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_796_save/RestoreV2_182", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

Caused by op 'save/RestoreV2_152', defined at:
  File "run_basics.py", line 13, in <module>
    prn = PRN(is_dlib = False)
  File "/home/ywang/PRNet/api.py", line 34, in __init__
    self.pos_predictor.restore('./'+prn_path)
  File "/home/ywang/PRNet/predictor.py", line 94, in restore
    tf.train.Saver(self.network.vars).restore(self.sess, model_path)
  File "/home/ywang/anaconda3/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1218, in __init__
    self.build()
  File "/home/ywang/anaconda3/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1227, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/ywang/anaconda3/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1263, in _build
    build_save=build_save, build_restore=build_restore)
  File "/home/ywang/anaconda3/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 751, in _build_internal
    restore_sequentially, reshape)
  File "/home/ywang/anaconda3/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 427, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/home/ywang/anaconda3/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 267, in restore_op
    [spec.tensor.dtype])[0])
  File "/home/ywang/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1021, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "/home/ywang/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/ywang/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/home/ywang/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

NotFoundError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ././Data/net-data/256_256_resfcn256_weight
         [[Node: save/RestoreV2_152 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_152/tensor_names, save/RestoreV2_152/shape_and_slices)]]
         [[Node: save/RestoreV2_182/_303 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_796_save/RestoreV2_182", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

please help me

**Comment by wungemach** [comment]
Did you download the data from GoogleDrive and put it in Data/net-data as instructed in the README?

**Comment by Morceguito** [comment]
@wungemach  I have a similar error:
Unable to open table file /content/drive/MyDrive/PRNet-Depth-Generation-master/Data/net-data/256_256_resfcn256_weight.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?

I also had to change the code in api.py in line 41 self.pos_predictor.restore(prn_path + '.data-00000-of-00001') adding the '.data-00000-of-00001' or would say the file did not existed. Can you tell me what am I doing wrong? The data is on Data/net-data
