### ISSUE TITLE
FileNotFoundError when running run_basics.py and no output

### ISSUE THREAD

**Issue by blvck-mvgic** [YadiraF/PRNet#47]
I didn't install dlib and opencv2 yet, idk if that's the issue
This is the output:
```
2018-07-05 23:05:51.604383: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1356] Found device 0 with properties:
name: GeForce GTX 1060 6GB major: 6 minor: 1 memoryClockRate(GHz): 1.7715
pciBusID: 0000:01:00.0
totalMemory: 6.00GiB freeMemory: 4.97GiB
2018-07-05 23:05:51.612427: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1435] Adding visible gpu devices: 0
2018-07-05 23:05:52.415988: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-07-05 23:05:52.420490: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:929]      0
2018-07-05 23:05:52.423549: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:942] 0:   N
2018-07-05 23:05:52.427180: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4740 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1060 6GB, pci bus id: 0000:01:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "run_basics.py", line 51, in <module>
    np.savetxt(os.path.join(save_folder, name + '.txt'), kpt)
  File "C:\Users\fede\env\PRnet\lib\site-packages\numpy\lib\npyio.py", line 1307, in savetxt
    open(fname, 'wt').close()
FileNotFoundError: [Errno 2] No such file or directory: 'TestImages/AFLW2000_results\\AFLW2000\\image00050.txt'
```
Also there are no images in the \TestImages\AFLW2000_results folder.

**Comment by jcho6** [comment]
There is a funky little issue with the how program works. 

Try going to the AFLW2000_results folder and create a new folder named AFLW2000

That should get the program working.
